language: r

# Be strict when checking our package
warnings_are_errors: true

# System dependencies for HTTP calling
apt_packages:
 - libcurl4-openssl-dev
 - libxml2-dev
r_binary_packages:
 - svUnit
 - dplyr

# Install the bleeding edge version of a package from github (eg to pick
# up a not-yet-released bugfix)
# readr is to read csv, tsv and fwf into R
r_github_packages:
 - hadley/readr


## Sample .travis.yml for R projects.
##
## See README.md for instructions, or for more configuration options,
## see the wiki:
##   https://github.com/craigcitro/r-travis/wiki
#
#language: c
#
#env:
#  global:
#    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
#    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
##    - RunAllRcppTests="yes"
#    - CRAN="http://cran.us.r-project.org"
#
#before_install:
#  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
#  - chmod 755 ./travis-tool.sh
#  - ./travis-tool.sh bootstrap
#  - sudo add-apt-repository -y ppa:edd/misc
#  - sudo apt-get update -q
#
#install:
#  - ./travis-tool.sh install_aptget r-cran-runit r-cran-inline r-cran-rbenchmark r-cran-highlight r-cran-pkgkitten
#
#script: 
#  - ./travis-tool.sh run_tests
#
#after_failure:
#  - ./travis-tool.sh dump_logs
#
#notifications:
#  email:
#    on_success: change
#    on_failure: change
